# Generated by Django 5.0.6 on 2024-05-22 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('anul', models.DateTimeField(auto_now_add=True)),
                ('producator', models.CharField(max_length=200)),
                ('procesor', models.CharField(max_length=30)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', max_length=300, null=True, upload_to='images/telefon/')),
                ('telefon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefon.telefon')),
            ],
        ),
    ]
