# Generated by Django 5.0.6 on 2024-05-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', max_length=300, null=True, upload_to='telefon/'),
        ),
    ]
