# Generated by Django 5.0.6 on 2024-05-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('anul', models.DateTimeField(auto_now_add=True)),
                ('producator', models.CharField(max_length=200)),
                ('procesor', models.CharField(max_length=30)),
                ('descriere', models.TextField()),
                ('price', models.FloatField()),
                ('greutatea', models.FloatField()),
                ('image', models.ImageField(default='', max_length=300, null=True, upload_to='laptop/')),
            ],
        ),
    ]
