# Generated by Django 5.0.6 on 2024-05-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Telefon',
            new_name='Laptop',
        ),
    ]
